### ISSUE TITLE
Anyway to pass parameters to the desired window?

### ISSUE THREAD

**Issue by Madcheese101** [mike-eason/MVVM_WindowCommands#1]
Hi, 
I have a child window that has a few parameters in its constructor and I would like to use your method.

I have made a few changes to your code. so instead of using commands, I am using an Interface to call from later on from any method that might need it.

here's my code: 

       public void ShowWindow(object windowname)
        {
           
            TypeInfo w = (TypeInfo)windowname;
            Type t = windowname.GetType();
            if(w.BaseType != typeof(Window))
                throw new InvalidOperationException("parameter is not a Window type");

            Window wnd = Activator.CreateInstance(w) as Window;

            wnd.Show();
        }
        
currently, I am using a non-dynamic way to do it from the same Interface, this is an example of it:

        public void report(int param1, string param2)
        {
            UI.window2 wn = new UI.window2(param1, param2);

            wn.Show();
        }

Thank you in advance.

**Comment by mike-eason** [comment]
Hi there,

`Activator.CreateInstance` has an override method that allows you to pass in constructor parameters:

```
(T)Activator.CreateInstance(typeof(T), param1, param2);
```

See here: https://stackoverflow.com/questions/2451336/how-to-pass-parameters-to-activator-createinstancet

**Comment by Madcheese101** [comment]
Thank you very much for the fast reply. now it works perfectly and also dynamically. But I have a concern of breaking the MVVM pattern by using this code in my MainwindowViewModel:
`_windowServices.ShowWindow(typeof(ChildWindow), new object[] { param1, param2 });`

I am totally new to MVVM so I get confused sometimes.

**Comment by Madcheese101** [comment]
Thank you very much. It works perfectly now :D
